### PR TITLE
Apply patch from SDK

### PR DESCRIPTION
**Pull request by shamsasari**
Markers have been added around each modification to make it easier to track our changes when merge conflicts with upstream occur.

### CODE REVIEW

**Review by ac101m — APPROVED** [review]
Looks good to me!

**Comment by ac101m** [comment]
> Looks good to me!

Whoops, didn't notice this was still WIP.

**Comment by shamsasari** [comment]
This will merge after #2

**Comment by filipesoliveira** [comment]
It looks OK.

**Comment by shamsasari** [comment]
Just updated the patch with `Conclave start` and `Conclave end` comments surrounding our modifications.

**Comment by anien** [comment]
LGTM.

**Comment by shamsasari** [comment]
@filipesoliveira in the standup we said that we would commit the patch to the repo. Just to be clear, we're not committing the actual patch file, but applying the diff as a PR here. Sorry for the confusion.

**Pull request merged**
